GET  http://localhost:3001/cars
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzE4MTkyMjcxLCJleHAiOjE3MTgxOTIzMzF9.aD77-KNTs6Jp_g8aWispQm3qU_0oGZph6l8EFTCRi_4

###
GET  http://localhost:3001/token

###
POST http://localhost:3001/login
Content-Type: application/json

{
    "username": "edi123",
    "password": "edi123"
}